Name:           ros-kinetic-cob-moveit-bringup
Version:        0.7.0
Release:        0%{?dist}
Summary:        ROS cob_moveit_bringup package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-cob-hardware-config
Requires:       ros-kinetic-cob-moveit-config
Requires:       ros-kinetic-joint-state-publisher
Requires:       ros-kinetic-moveit-planners-ompl
Requires:       ros-kinetic-moveit-plugins
Requires:       ros-kinetic-moveit-ros-move-group
Requires:       ros-kinetic-moveit-ros-perception
Requires:       ros-kinetic-moveit-ros-visualization
Requires:       ros-kinetic-moveit-setup-assistant
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-catkin

%description
MoveIt launch files

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Aug 05 2017 Mathias Luedtke <mdl@ipa.fhg.de> - 0.7.0-0
- Autogenerated by Bloom

