Name:           ros-kinetic-cob-obstacle-distance-moveit
Version:        0.7.0
Release:        0%{?dist}
Summary:        ROS cob_obstacle_distance_moveit package

Group:          Development/Libraries
License:        LGPL
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       fcl-devel
Requires:       pkgconfig
Requires:       ros-kinetic-cob-control-msgs
Requires:       ros-kinetic-cob-srvs
Requires:       ros-kinetic-eigen-conversions
Requires:       ros-kinetic-geometric-shapes
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-moveit-core
Requires:       ros-kinetic-moveit-msgs
Requires:       ros-kinetic-moveit-ros-perception
Requires:       ros-kinetic-moveit-ros-planning-interface
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-tf-conversions
BuildRequires:  boost-devel
BuildRequires:  fcl-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cob-control-msgs
BuildRequires:  ros-kinetic-cob-srvs
BuildRequires:  ros-kinetic-eigen-conversions
BuildRequires:  ros-kinetic-geometric-shapes
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-moveit-core
BuildRequires:  ros-kinetic-moveit-msgs
BuildRequires:  ros-kinetic-moveit-ros-perception
BuildRequires:  ros-kinetic-moveit-ros-planning-interface
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-tf-conversions

%description
This package provides nodes for calculating the minimal distance to robot links,
obstacles and octomap using MoveIt!'s PlanningSceneMonitor

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Aug 05 2017 Felix Messmer <fxm@ipa.fhg.de> - 0.7.0-0
- Autogenerated by Bloom

